name: novaforge_starter
description: "Production-ready template for Flutter applications"
publish_to: 'none'
version: 0.0.1

resolution: workspace

#homepage: https://github.com/
#repository: https://github.com/
#issue_tracker: https://github.com/

#funding:
#  - https://www.buymeacoffee.com/
#  - https://www.patreon.com/
#  - https://boosty.to/

#topics:
#  -
#  -

#platforms:
#  android:
#  ios:
#  linux:
#  macos:
#  web:
#  windows:

#screenshots:
#  - description: 'Screenshot 1'
#    path: screenshot_1.png

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
